CREATE TABLE academies (
    academy_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    academy_name VARCHAR(150) NOT NULL,
    academy_email VARCHAR(150) NOT NULL UNIQUE,
    academy_phone VARCHAR(30),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    academy_id BIGINT NOT NULL,
    user_name VARCHAR(150) NOT NULL,
    user_email VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(30) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_users_academy
        FOREIGN KEY (academy_id)
        REFERENCES academies (academy_id),

    CONSTRAINT chk_users_role
        CHECK (role IN ('ADMIN', 'TEACHER', 'STUDENT'))
);

CREATE TABLE student_profiles (
    profile_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    birth_date DATE,
    student_phone VARCHAR(30),
    goal VARCHAR(80),
    notes TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_student_profiles_user
        FOREIGN KEY (user_id)
        REFERENCES users (user_id),

    CONSTRAINT uk_student_profiles_user
        UNIQUE (user_id)
);

CREATE TABLE exercises (
    exercise_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    academy_id BIGINT NOT NULL,
    exercise_name VARCHAR(120) NOT NULL,
    muscle_group VARCHAR(80),
    description TEXT,
    equipment_name VARCHAR(120),
    image_url TEXT,
    video_url TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_exercises_academy
        FOREIGN KEY (academy_id)
        REFERENCES academies (academy_id),

    CONSTRAINT uk_exercises_academy_name
        UNIQUE (academy_id, exercise_name)
);

CREATE TABLE workouts (
    workout_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    teacher_id BIGINT NOT NULL,
    workout_name VARCHAR(120) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_workouts_student
        FOREIGN KEY (student_id)
        REFERENCES users (user_id),

    CONSTRAINT fk_workouts_teacher
        FOREIGN KEY (teacher_id)
        REFERENCES users (user_id),

    CONSTRAINT chk_workouts_status
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'ARCHIVED'))
);

CREATE TABLE workout_exercises (
    workout_exercise_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_id BIGINT NOT NULL,
    exercise_id BIGINT NOT NULL,
    exercise_order INTEGER NOT NULL,
    sets INTEGER NOT NULL,
    reps INTEGER NOT NULL,
    recommended_load NUMERIC(6,2),
    rest_time_seconds INTEGER,
    notes TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_workout_exercises_workout
        FOREIGN KEY (workout_id)
        REFERENCES workouts (workout_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_workout_exercises_exercise
        FOREIGN KEY (exercise_id)
        REFERENCES exercises (exercise_id),

    CONSTRAINT uk_workout_exercises_order
        UNIQUE (workout_id, exercise_order),

    CONSTRAINT chk_workout_exercises_sets
        CHECK (sets > 0),

    CONSTRAINT chk_workout_exercises_reps
        CHECK (reps > 0),

    CONSTRAINT chk_workout_exercises_order
        CHECK (exercise_order > 0)
);